namespace Oryxen.Domain.Enums;

/// <summary>
/// Category of a notification generated by the Oryxen platform. Each type drives the
/// title, message template and delivery channel selection.
/// </summary>
public enum NotificationType
{
    CriticalHealth = 1,
    HighAnomalies = 2,
    WateringReminder = 3,
    SystemUpdate = 4
}
