using Oryxen.Domain.Common;
using Oryxen.Domain.Enums;

namespace Oryxen.Domain.Entities;

/// <summary>
/// Aggregate root of the Notification bounded context. Represents an alert or reminder
/// generated by the system for a specific user, optionally linked to a plant. Notifications
/// are created automatically when critical telemetry conditions are detected (e.g.
/// HealthScore &lt; 40) or when AI diagnoses complete, and can also be dispatched via
/// external channels (email, push).
/// </summary>
public class Notification : AuditableEntity
{
    public Guid UserId { get; set; }

    public Guid? PlantId { get; set; }

    public NotificationType Type { get; set; }

    public NotificationChannel Channel { get; set; } = NotificationChannel.InApp;

    public string Title { get; set; } = string.Empty;

    public string Message { get; set; } = string.Empty;

    public bool IsRead { get; set; }

    public DateTime? SentAt { get; set; }
}
