using Oryxen.Domain.Common;
using Oryxen.Domain.Enums;

namespace Oryxen.Domain.Entities;

/// <summary>
/// Aggregate root of the Artificial Intelligence bounded context. Represents the result
/// of a multimodal plant health analysis performed on a photograph enriched with the
/// latest Sensor Lite telemetry. The analysis targets the detection of general plant
/// anomalies (diseases, pests, nutrient deficiencies, water stress) and returns a
/// confidence score together with a care or mitigation recommendation.
/// </summary>
public class PlantDiagnosis : AuditableEntity
{
    public Guid PlantId { get; set; }

    /// <summary>Reference to the uploaded crop photograph (URL or data-URI marker).</summary>
    public string ImageUrl { get; set; } = string.Empty;

    /// <summary>Detected anomaly or pest name returned by the multimodal model, e.g. "Powdery Mildew" or "None".</summary>
    public string DetectedPest { get; set; } = string.Empty;

    /// <summary>Model confidence in the range 0.0–1.0.</summary>
    public double ConfidenceScore { get; set; }

    /// <summary>Care or mitigation recommendation generated by the model based on the visual and telemetry analysis.</summary>
    public string Recommendation { get; set; } = string.Empty;

    public DiagnosisStatus Status { get; set; } = DiagnosisStatus.Pending;

    /// <summary>UTC instant when the Gemini Vision API returned the analysis. Null while pending.</summary>
    public DateTime? AnalyzedAt { get; set; }
}
