using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Oryxen.Application.Analytics;
using Oryxen.Application.Analytics.Contracts;
using Oryxen.Domain.Constants;

namespace Oryxen.API.Controllers;

/// <summary>
/// Analysis &amp; Reporting bounded context: aggregated dashboards, plant health
/// trends and on-demand report generation from historical IoT telemetry.
/// </summary>
[ApiController]
[Route("api/v1/analytics")]
[Produces("application/json")]
[Authorize(Roles = $"{Roles.Farmer},{Roles.Admin}")]
public sealed class AnalyticsController : ControllerBase
{
    private readonly IAnalysisService _analysisService;

    public AnalyticsController(IAnalysisService analysisService) => _analysisService = analysisService;

    /// <summary>
    /// Returns the consolidated analytic dashboard for the authenticated farmer,
    /// including health summaries of all owned plants over the last 30 days.
    /// </summary>
    [HttpGet("dashboard")]
    [ProducesResponseType(typeof(DashboardResponse), StatusCodes.Status200OK)]
    public async Task<ActionResult<DashboardResponse>> GetDashboard(CancellationToken cancellationToken)
    {
        var userId = CurrentUserId;
        return Ok(await _analysisService.GetDashboardAsync(userId, cancellationToken));
    }

    /// <summary>
    /// Returns aggregated health, soil moisture, temperature and humidity trends
    /// for a single plant, grouped daily, weekly and monthly.
    /// </summary>
    [HttpGet("plants/{plantId:guid}/trends")]
    [ProducesResponseType(typeof(PlantTrendResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<PlantTrendResponse>> GetPlantTrends(
        Guid plantId,
        CancellationToken cancellationToken)
    {
        var result = await _analysisService.GetPlantTrendsAsync(plantId, cancellationToken);
        if (string.IsNullOrEmpty(result.PlantName))
        {
            return NotFound();
        }

        return Ok(result);
    }

    /// <summary>
    /// Lists the analytic reports generated by the authenticated user,
    /// optionally filtered by a specific plant.
    /// </summary>
    [HttpGet("reports")]
    [ProducesResponseType(typeof(ReportListResponse), StatusCodes.Status200OK)]
    public async Task<ActionResult<ReportListResponse>> GetReports(
        [FromQuery] Guid? plantId = null,
        [FromQuery] int page = 1,
        [FromQuery] int size = 20,
        CancellationToken cancellationToken = default)
    {
        return Ok(await _analysisService.GetReportsAsync(CurrentUserId, plantId, page, size, cancellationToken));
    }

    /// <summary>
    /// Returns the full content of a previously generated report.
    /// </summary>
    [HttpGet("reports/{reportId:guid}")]
    [ProducesResponseType(typeof(ReportDetailResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ReportDetailResponse>> GetReportById(
        Guid reportId,
        CancellationToken cancellationToken)
    {
        var report = await _analysisService.GetReportByIdAsync(reportId, cancellationToken);
        if (report is null)
        {
            return NotFound();
        }

        return Ok(report);
    }

    /// <summary>
    /// Generates a new analytic report on demand for a plant and time range.
    /// The report content is returned inline in CSV or JSON format.
    /// </summary>
    [HttpPost("reports")]
    [ProducesResponseType(typeof(ReportDetailResponse), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GenerateReport(
        [FromBody] GenerateReportRequest request,
        CancellationToken cancellationToken)
    {
        if (request.RangeStart >= request.RangeEnd)
        {
            return BadRequest("RangeStart must be before RangeEnd.");
        }

        var result = await _analysisService.GenerateReportAsync(CurrentUserId, request, cancellationToken);
        return Created($"/api/v1/analytics/reports/{result.Id}", result);
    }

    private Guid CurrentUserId => Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
}
